; HEADER_BLOCK_START
; generated by OrcaSlicer 1.6.3 on 2023-07-22 at 20:56:14
; total layer number: 1
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START
; thumbnail begin 300x300 2260
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAGZElEQVR4Ae3cP6pk1RbA4TMGQRAMOr
; ETA/8k3QqCrYE0YqJgZNSYCoIjaByBidCOQDAyN7ipiWNwKG0fr7e7rFt1q+qcffZea+/vg1/2svtY
; b+316vQ0AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAARff/gracfvPnaowkgsnlY/f3d4+dzv3754GoCiGZ3UO02Dy3b
; FhDGsWG12/yfmQBamjeoU8PKtgU0dc5WZdsCmlszrBzkgSpKDKr9PBGB4rYYVp6IQFHzBnTJYX3NE9
; G2BSy25VZl2wKKaTGsHOSBi7QcVPt5IgJHRRpWnojAQfMmE21Q7T8RbVtAyK3KtgXcUuPnCrYtYJVM
; W5VtCwbWw7Da3bYmoD89Dar9PBGhIz0Pq5s8ESG5Wt8BRslBHpIaYauybUEHRh5Wu9vWBMRlUN3OEx
; ECMqyO54kIQUT/DjBKDvLQmK3q8mxb0IBhtTzbFlRiUJXL0IINGVbl8/MHKMyg2n5o2bagAMOqXg7y
; sNBo3wFGybYFF7JVtc+2BWcwrOLkIA9HGFRx80SEHYZV/DwRGZ7Deq4c5BmWrSpvti2GYljlz7ZF9w
; yq/jK06JJh1W+eiHTDoBojT0TSM6zGy7ZFSn6uMG62LdKwVekm2xahGVbaz/eIhGNQ6VSeiIRgWOnc
; PBFpxneAWpKDPNXZqrQ22xZVGFYqlYM8mzGotFWeiBRlWGnrPBFZbf5fvkz/pVfuHORZzFalVtm2uI
; hhpdbZtjjJoFK0bFscZFgpan7+wEsGlTLkiYhhpXR5Ig7Id4DKnG1rILYq9ZJtq3OGlXrLQb5DBpV6
; zxOxE4aVRskTMTGHdY2Yg3xCtiqNnm0rCcNKus62FZhBJR3O0ArGsJLuzhMxAINKOj9PxIYMK2lZtq
; 3K/FxBWpdtqwJblVQ229ZGDCtpm3yPWJBBJdXJE3Elw0qqmyfiAr4DlNrlIH8BW5UUI9vWCYaVFCsH
; +QMMKil2noj/MaykHA39RJwndqY/lqRBD/K2Kil3w2xbPz9+7yrTH0bS4X767J3+D/I/PLx/9cc3H6
; X6w0j6f79//eHzJ+/eG+f/Qfztq4ep/kCSrpuH1TSiedv669tPU/2xpFGbB9WPH7895rC68cX9N556
; Ikqxm4fVJ/defzpxbX4i2rakWP355JGt6hgHeSlOtqoz2baktg17WF/KtiXVb7ifK5Q0H+T9/EGqky
; dgIZ6I0nb5ucIGPBGl8tmqNmbbktY3/1zhl8/ft1XVYNuSluew3oCDvHR5noCN+R5ROp3DeiC+R5SO
; Z6sKykFeepXDegIO8pKtKh3blkbNd4BJOchrpPxcoQN+/qAR8gTsjCeieszPFTrmIK+eslUNwral7P
; m5wmBsW8qYw/rAHOSVKU9A/uXnD4qcwzq3eCIqYrYq7uQgrwj5DpCz2bbUMlsVi9i2VDvfAbKKg7xq
; 5LBOMf6BQG2ZJyCb8ERUyebDuq2KTTnIq0S2KqqybWlpfq5AE7YtXZLvAGnO94g6J09AQnn2Ys33RN
; R+fq5AWJ6I2s1WRQoO8mPnO0DSsW2NmcM6aTnIjzesPAFJz/eI/Q8qh3W64nvEfoeVrYpuOcj3ke8A
; GYaDfO5sVQzJtpVzWE0wKttWnkHl5wow+flDhmHlCQh7PBHjDSqHdbiDJ2KcYWWrgjPZttrkO0BYyL
; ZVN4d1WMlBvt6w8gSEQnyPuN2gcliHDXgilh9WtirYmIP8uhzWoTLb1rJsVdCQbeuyYTUBbTnInx5U
; DusQiH8g8Piw8gSEoDwRXw0qWxUkMPpB3lYFCY24bfm5AiQ2yrblO0DoRO/fI3oCQoeevXgu9fREdF
; iHzvXyRLRVwUCyHuR9BwiDyrZtOazD4LIc5D0BgZeifo/osA4cFO17RFsVcFLrg/x8WLdVAWdrdZC3
; VQGL1dy2/AN7wGpbb1t+rgAUtdXPHzwBgc2UeiL6uQJQxdonoq0KqO7Sbct3gEBT525bDutACKcO8p
; 6AQDj73yM6rAOh3TwRbVUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMBa/wBC7rPSpKEmwwAAAABJRU5ErkJggg==
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=Cube_id_0_copy_0 CENTER=130,110 POLYGON=[[117,97],[143,97],[143,123],[117,123],[117,97]]
M73 P0 R1
;TYPE:Custom
START_PRINT EXTRUDER_TEMP=220 BED_TEMP=60 RELATIVE_E_MODE=1 PRESSURE_ADVANCE=0.06
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
SET_PRESSURE_ADVANCE ADVANCE=0.06; Override pressure advance value
M106 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 E-1 F1800
G1 Z.4 F9000
G1 X114.639 Y95.583
M73 P1 R1
G1 Z.2
G1 E1 F1800
;TYPE:Skirt
;WIDTH:0.42
G1 F900
G1 X115.705 Y94.569 E.04519
G1 X117 Y94.246 E.04102
M73 P2 R1
G1 X143 Y94.246 E.79891
M73 P4 R1
G1 X144.417 Y94.639 E.04519
G1 X145.431 Y95.705 E.04519
G1 X145.754 Y97 E.04102
G1 X145.754 Y123 E.79891
M73 P6 R1
G1 X145.361 Y124.417 E.04519
G1 X144.295 Y125.431 E.04519
G1 X143 Y125.754 E.04102
G1 X117 Y125.754 E.79891
M73 P8 R1
G1 X115.583 Y125.361 E.04519
M73 P9 R1
G1 X114.569 Y124.295 E.04519
G1 X114.246 Y123 E.04102
G1 X114.246 Y97 E.79891
M73 P11 R1
G1 X114.623 Y95.64 E.04335
G1 X114.997 Y95.752 F9000
G1 F900
G1 X115.015 Y95.693 E.00191
G1 X116.06 Y94.817 E.04193
G1 X117 Y94.623 E.02948
G1 X143 Y94.623 E.79891
M73 P13 R1
G1 X144.307 Y95.015 E.04193
G1 X145.183 Y96.06 E.04193
M73 P14 R1
G1 X145.377 Y97 E.02948
G1 X145.377 Y123 E.79891
M73 P16 R1
G1 X144.985 Y124.307 E.04193
G1 X143.94 Y125.183 E.04193
G1 X143 Y125.377 E.02948
G1 X117 Y125.377 E.79891
M73 P18 R1
G1 X115.693 Y124.985 E.04193
G1 X114.817 Y123.94 E.04193
G1 X114.623 Y123 E.02948
G1 X114.623 Y97 E.79891
M73 P21 R1
G1 X114.979 Y95.81 E.03817
; printing object Cube id:0 copy 0
EXCLUDE_OBJECT_START NAME=Cube_id_0_copy_0
G1 E-.7 F1800
;WIPE_START
G1 F900
G1 X115.015 Y95.693 E-.0174
G1 X116.06 Y94.817 E-.19443
G1 X116.563 Y94.713 E-.07317
;WIPE_END
G1 E-.015 F1800
G1 Z.6 F9000
G1 X142.313 Y122.313 Z.2
M73 P22 R1
G1 E1 F1800
;TYPE:Inner wall
;WIDTH:0.419999
G1 F900
G1 X117.687 Y122.313 E.75668
M73 P24 R1
G1 X117.687 Y97.687 E.75668
M73 P26 R1
G1 X142.313 Y97.687 E.75668
M73 P28 R1
G1 X142.313 Y110 E.37834
M73 P29 R0
G1 X142.313 Y122.253 E.3765
M73 P30 R0
G1 X142.69 Y122.69 F9000
;TYPE:Outer wall
G1 F900
G1 X117.31 Y122.69 E.77986
M73 P32 R0
G1 X117.31 Y97.31 E.77986
M73 P34 R0
G1 X142.69 Y97.31 E.77986
M73 P36 R0
G1 X142.69 Y110 E.38993
M73 P37 R0
G1 X142.69 Y122.63 E.38808
M73 P38 R0
G1 X142.621 Y122.65
G1 E-.7 F1800
;WIPE_START
G1 F900
G1 X140.69 Y122.635 E-.285
;WIPE_END
G1 E-.015 F1800
G1 Z.6 F9000
G1 X141.432 Y97.8 Z.2
M73 P39 R0
G1 E1 F1800
;TYPE:Bottom surface
;WIDTH:0.422695
G1 F2100
G1 X142.03 Y98.398 E.02618
G1 X142.03 Y98.936 E.01662
G1 X141.064 Y97.97 E.04226
G1 X140.527 Y97.97 E.01662
G1 X142.03 Y99.473 E.06577
G1 X142.03 Y100.01 E.01662
G1 X139.99 Y97.97 E.08928
G1 X139.453 Y97.97 E.01662
G1 X142.03 Y100.547 E.11278
M73 P40 R0
G1 X142.03 Y101.084 E.01662
G1 X138.916 Y97.97 E.13629
G1 X138.379 Y97.97 E.01662
G1 X142.03 Y101.621 E.15979
G1 X142.03 Y102.158 E.01662
G1 X137.842 Y97.97 E.1833
G1 X137.305 Y97.97 E.01662
G1 X142.03 Y102.695 E.2068
M73 P41 R0
G1 X142.03 Y103.232 E.01662
G1 X136.768 Y97.97 E.23031
G1 X136.231 Y97.97 E.01662
G1 X142.03 Y103.769 E.25382
G1 X142.03 Y104.306 E.01662
G1 X135.694 Y97.97 E.27732
M73 P42 R0
G1 X135.157 Y97.97 E.01662
G1 X142.03 Y104.843 E.30083
G1 X142.03 Y105.381 E.01662
G1 X134.619 Y97.97 E.32433
M73 P43 R0
G1 X134.082 Y97.97 E.01662
G1 X142.03 Y105.918 E.34784
G1 X142.03 Y106.455 E.01662
G1 X133.545 Y97.97 E.37134
M73 P44 R0
G1 X133.008 Y97.97 E.01662
G1 X142.03 Y106.992 E.39485
G1 X142.03 Y107.529 E.01662
G1 X132.471 Y97.97 E.41836
M73 P45 R0
G1 X131.934 Y97.97 E.01662
G1 X142.03 Y108.066 E.44186
G1 X142.03 Y108.603 E.01662
G1 X131.397 Y97.97 E.46537
M73 P46 R0
G1 X130.86 Y97.97 E.01662
G1 X142.03 Y109.14 E.48887
M73 P47 R0
G1 X142.03 Y109.677 E.01662
G1 X130.323 Y97.97 E.51238
G1 X129.786 Y97.97 E.01662
G1 X142.03 Y110.214 E.53588
M73 P48 R0
G1 X142.03 Y110.751 E.01662
G1 X129.249 Y97.97 E.55939
M73 P49 R0
G1 X128.712 Y97.97 E.01662
G1 X142.03 Y111.288 E.58289
G1 X142.03 Y111.826 E.01662
G1 X128.174 Y97.97 E.6064
M73 P50 R0
G1 X127.637 Y97.97 E.01662
G1 X142.03 Y112.363 E.62991
M73 P51 R0
G1 X142.03 Y112.9 E.01662
G1 X127.1 Y97.97 E.65341
M73 P52 R0
G1 X126.563 Y97.97 E.01662
G1 X142.03 Y113.437 E.67692
M73 P53 R0
G1 X142.03 Y113.974 E.01662
G1 X126.026 Y97.97 E.70042
G1 X125.489 Y97.97 E.01662
G1 X142.03 Y114.511 E.72393
M73 P54 R0
G1 X142.03 Y115.048 E.01662
G1 X124.952 Y97.97 E.74743
M73 P55 R0
G1 X124.415 Y97.97 E.01662
G1 X142.03 Y115.585 E.77094
M73 P56 R0
G1 X142.03 Y116.122 E.01662
G1 X123.878 Y97.97 E.79445
M73 P57 R0
G1 X123.341 Y97.97 E.01662
G1 X142.03 Y116.659 E.81795
M73 P58 R0
G1 X142.03 Y117.196 E.01662
G1 X122.804 Y97.97 E.84146
M73 P59 R0
G1 X122.267 Y97.97 E.01662
G1 X142.03 Y117.733 E.86496
M73 P60 R0
G1 X142.03 Y118.271 E.01662
G1 X121.729 Y97.97 E.88847
M73 P61 R0
G1 X121.192 Y97.97 E.01662
G1 X142.03 Y118.808 E.91197
M73 P62 R0
G1 X142.03 Y119.345 E.01662
G1 X120.655 Y97.97 E.93548
M73 P64 R0
G1 X120.118 Y97.97 E.01662
G1 X142.03 Y119.882 E.95899
M73 P65 R0
G1 X142.03 Y120.419 E.01662
G1 X119.581 Y97.97 E.98249
M73 P66 R0
G1 X119.044 Y97.97 E.01662
G1 X142.03 Y120.956 E1.006
M73 P67 R0
G1 X142.03 Y121.493 E.01662
G1 X118.507 Y97.97 E1.0295
M73 P68 R0
G1 X117.97 Y97.97 E.01662
G1 X142.03 Y122.03 E1.05301
M73 P70 R0
G1 X141.493 Y122.03 E.01662
G1 X117.97 Y98.507 E1.0295
M73 P71 R0
G1 X117.97 Y99.044 E.01662
G1 X140.956 Y122.03 E1.006
M73 P72 R0
G1 X140.419 Y122.03 E.01662
G1 X117.97 Y99.581 E.98249
M73 P73 R0
G1 X117.97 Y100.118 E.01662
G1 X139.882 Y122.03 E.95898
M73 P74 R0
G1 X139.345 Y122.03 E.01662
G1 X117.97 Y100.655 E.93548
M73 P76 R0
G1 X117.97 Y101.192 E.01662
G1 X138.808 Y122.03 E.91197
M73 P77 R0
G1 X138.271 Y122.03 E.01662
G1 X117.97 Y101.729 E.88847
M73 P78 R0
G1 X117.97 Y102.267 E.01662
G1 X137.733 Y122.03 E.86496
M73 P79 R0
G1 X137.196 Y122.03 E.01662
G1 X117.97 Y102.804 E.84146
M73 P80 R0
G1 X117.97 Y103.341 E.01662
G1 X136.659 Y122.03 E.81795
M73 P81 R0
G1 X136.122 Y122.03 E.01662
G1 X117.97 Y103.878 E.79444
M73 P82 R0
G1 X117.97 Y104.415 E.01662
G1 X135.585 Y122.03 E.77094
M73 P83 R0
G1 X135.048 Y122.03 E.01662
G1 X117.97 Y104.952 E.74743
M73 P84 R0
G1 X117.97 Y105.489 E.01662
G1 X134.511 Y122.03 E.72393
M73 P85 R0
G1 X133.974 Y122.03 E.01662
G1 X117.97 Y106.026 E.70042
G1 X117.97 Y106.563 E.01662
G1 X133.437 Y122.03 E.67692
M73 P86 R0
G1 X132.9 Y122.03 E.01662
G1 X117.97 Y107.1 E.65341
M73 P87 R0
G1 X117.97 Y107.637 E.01662
G1 X132.363 Y122.03 E.6299
M73 P88 R0
G1 X131.826 Y122.03 E.01662
G1 X117.97 Y108.174 E.6064
M73 P89 R0
G1 X117.97 Y108.712 E.01662
G1 X131.288 Y122.03 E.58289
G1 X130.751 Y122.03 E.01662
G1 X117.97 Y109.249 E.55939
M73 P90 R0
G1 X117.97 Y109.786 E.01662
G1 X130.214 Y122.03 E.53588
M73 P91 R0
G1 X129.677 Y122.03 E.01662
G1 X117.97 Y110.323 E.51238
G1 X117.97 Y110.86 E.01662
G1 X129.14 Y122.03 E.48887
M73 P92 R0
G1 X128.603 Y122.03 E.01662
G1 X117.97 Y111.397 E.46536
M73 P93 R0
G1 X117.97 Y111.934 E.01662
G1 X128.066 Y122.03 E.44186
G1 X127.529 Y122.03 E.01662
G1 X117.97 Y112.471 E.41835
M73 P94 R0
G1 X117.97 Y113.008 E.01662
G1 X126.992 Y122.03 E.39485
G1 X126.455 Y122.03 E.01662
G1 X117.97 Y113.545 E.37134
M73 P95 R0
G1 X117.97 Y114.082 E.01662
G1 X125.918 Y122.03 E.34784
G1 X125.381 Y122.03 E.01662
G1 X117.97 Y114.619 E.32433
M73 P96 R0
G1 X117.97 Y115.157 E.01662
G1 X124.843 Y122.03 E.30083
G1 X124.306 Y122.03 E.01662
G1 X117.97 Y115.694 E.27732
M73 P97 R0
G1 X117.97 Y116.231 E.01662
G1 X123.769 Y122.03 E.25381
G1 X123.232 Y122.03 E.01662
G1 X117.97 Y116.768 E.23031
G1 X117.97 Y117.305 E.01662
G1 X122.695 Y122.03 E.2068
M73 P98 R0
G1 X122.158 Y122.03 E.01662
G1 X117.97 Y117.842 E.1833
G1 X117.97 Y118.379 E.01662
G1 X121.621 Y122.03 E.15979
G1 X121.084 Y122.03 E.01662
G1 X117.97 Y118.916 E.13629
G1 X117.97 Y119.453 E.01662
M73 P99 R0
G1 X120.547 Y122.03 E.11278
G1 X120.01 Y122.03 E.01662
G1 X117.97 Y119.99 E.08927
G1 X117.97 Y120.527 E.01662
G1 X119.473 Y122.03 E.06577
G1 X118.936 Y122.03 E.01662
G1 X117.97 Y121.064 E.04226
G1 X117.97 Y121.602 E.01662
G1 X118.568 Y122.2 E.02618
; stop printing object Cube id:0 copy 0
EXCLUDE_OBJECT_END NAME=Cube_id_0_copy_0
G1 E-.7 F1800
;WIPE_START
G1 F2100
G1 X117.97 Y121.602 E-.12057
G1 X117.97 Y121.064 E-.07653
G1 X118.406 Y121.501 E-.0879
;WIPE_END
G1 E-.015 F1800
M106 S0
;TYPE:Custom
; filament end gcode 
END_PRINT
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 62.16
; filament used [cm3] = 0.15
; filament used [g] = 0.19
; filament cost = 0.00; total filament used [g] = 0.19
; total filament cost = 0.00
; total layers count = 1
; estimated printing time (normal mode) = 1m 22s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 0
; accel_to_decel_factor = 50%
; additional_cooling_fan_speed = 70
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_temperature_difference = 10
; before_layer_change_gcode = 
; bottom_shell_layers = 5
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 0.95
; bridge_no_support = 0
; bridge_speed = 25
; brim_object_gap = 0
; brim_type = auto_brim
; brim_width = 0
; chamber_temperature = 0
; change_filament_gcode = M600
; close_fan_the_first_x_layers = 1
; cool_plate_temp = 60
; cool_plate_temp_initial_layer = 60
; curr_bed_type = High Temp Plate
; default_acceleration = 0
; default_filament_colour = ""
; default_filament_profile = "Creality Generic PLA"
; default_jerk = 0
; default_print_profile = 0.20mm Standard @Creality Ender6
; deretraction_speed = 30
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 1
; different_settings_to_system = ;enable_pressure_advance;pressure_advance;deretraction_speed;gcode_flavor;machine_end_gcode;machine_pause_gcode;machine_start_gcode;print_host;printable_area;printhost_ssl_ignore_revoke;retraction_length;retraction_speed
; draft_shield = disabled
; elefant_foot_compensation = 0.1
; enable_arc_fitting = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 1
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 60
; eng_plate_temp_initial_layer = 60
; ensure_vertical_shell_thickness = 1
; exclude_object = 1
; extruder_clearance_height_to_lid = 34
; extruder_clearance_height_to_rod = 34
; extruder_clearance_radius = 47
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; fan_cooling_layer_time = 100
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #F2754E
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_flow_ratio = 0.98
; filament_ids = GFL99
; filament_is_support = 0
; filament_max_volumetric_speed = 12
; filament_minimal_purge_on_wipe_tower = 15
; filament_settings_id = PLA
; filament_shrink = 100%
; filament_soluble = 0
; filament_start_gcode = "; filament start gcode\n"
; filament_type = PLA
; filament_vendor = Generic
; filename_format = [input_filename_base].gcode
; filter_out_gap_fill = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_infill_speed = 30
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; host_type = octoprint
; hot_plate_temp = 60
; hot_plate_temp_initial_layer = 60
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_direction = 45
; infill_jerk = 9
; infill_wall_overlap = 25%
; inherits_group = ;"Creality Generic PLA";"Creality Ender-6 0.4 nozzle"
; initial_layer_acceleration = 0
; initial_layer_infill_speed = 35
; initial_layer_jerk = 9
; initial_layer_line_width = 0.42
; initial_layer_print_height = 0.2
; initial_layer_speed = 15
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 0
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 40
; interface_shells = 0
; internal_bridge_support_thickness = 0
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0
; internal_solid_infill_speed = 50
; ironing_flow = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_change_gcode = 
; layer_height = 0.2
; line_width = 0.45
; machine_end_gcode = END_PRINT
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 500,500
; machine_max_acceleration_retracting = 1000,1000
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 500,500
; machine_max_acceleration_y = 500,500
; machine_max_acceleration_z = 100,100
; machine_max_jerk_e = 5,5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_max_speed_e = 60,60
; machine_max_speed_x = 500,500
; machine_max_speed_y = 500,500
; machine_max_speed_z = 10,10
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = PAUSE
; machine_start_gcode = START_PRINT EXTRUDER_TEMP=[nozzle_temperature_initial_layer] BED_TEMP=[hot_plate_temp_initial_layer] RELATIVE_E_MODE=[use_relative_e_distances] PRESSURE_ADVANCE=[pressure_advance]
; machine_unload_filament_time = 0
; max_bridge_length = 10
; max_layer_height = 0.28
; max_travel_detour_distance = 0
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; minimum_sparse_infill_area = 10
; nozzle_diameter = 0.4
; nozzle_hrc = 0
; nozzle_temperature = 220
; nozzle_temperature_initial_layer = 220
; nozzle_temperature_range_high = 230
; nozzle_temperature_range_low = 190
; nozzle_type = undefine
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; outer_wall_acceleration = 500
; outer_wall_jerk = 9
; outer_wall_line_width = 0.45
; outer_wall_speed = 40
; overhang_1_4_speed = 0
; overhang_2_4_speed = 20
; overhang_3_4_speed = 15
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_speed_classic = 0
; post_process = 
; precise_outer_wall = 0
; pressure_advance = 0.06
; prime_tower_brim_width = 3
; prime_tower_width = 60
; prime_volume = 45
; print_compatible_printers = "Creality Ender-6 0.4 nozzle"
; print_flow_ratio = 1
; print_host = 192.168.50.236
; print_host_webui = 
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @Creality Ender6
; printable_area = 0x0,260x0,260x220,0x220
; printable_height = 400
; printer_model = Creality Ender-6
; printer_settings_id = Ender Sex 0.4 nozzle
; printer_technology = FFF
; printer_variant = 0.4
; printhost_apikey = 
; printhost_authorization_type = key
; printhost_cafile = 
; printhost_password = 
; printhost_port = 
; printhost_ssl_ignore_revoke = 1
; printhost_user = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 70%
; retract_length_toolchange = 1
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_length = 1
; retraction_minimum_travel = 2
; retraction_speed = 30
; role_based_wipe_speed = 1
; scan_first_layer = 0
; seam_gap = 15%
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; skirt_distance = 2
; skirt_height = 2
; skirt_loops = 2
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 8
; slow_down_layers = 0
; slow_down_min_speed = 10
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = grid
; sparse_infill_speed = 60
; spiral_mode = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 0.2
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = -1
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_pattern = rectilinear
; support_interface_spacing = 0.2
; support_interface_speed = 80
; support_interface_top_layers = 3
; support_line_width = 0.38
; support_material_interface_fan_speed = -1
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_speed = 40
; support_style = grid
; support_threshold_angle = 45
; support_top_z_distance = 0.15
; support_type = normal(auto)
; temperature_vitrification = 60
; template_custom_gcode = 
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 60
; thick_bridges = 0
; thumbnails = 300x300
; timelapse_type = 0
; top_shell_layers = 7
; top_shell_thickness = 0.8
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 0
; top_surface_jerk = 9
; top_surface_line_width = 0.4
; top_surface_pattern = monotonic
; top_surface_speed = 30
; travel_acceleration = 0
; travel_jerk = 12
; travel_speed = 150
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_auto_brim = 1
; tree_support_branch_angle = 40
; tree_support_branch_diameter = 5
; tree_support_branch_distance = 5
; tree_support_brim_width = 3
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_infill_order = inner wall/outer wall/infill
; wall_loops = 2
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_distance = 2
; wipe_on_loops = 1
; wipe_speed = 80%
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 155.000
; wipe_tower_y = 220.000
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Normal Lift
; first_layer_bed_temperature = 60
; bed_shape = 0x0,260x0,260x220,0x220
; first_layer_temperature = 220
; first_layer_height = 0.200
; CONFIG_BLOCK_END


